### ISSUE TITLE
Regarding a feature for comparing Kachua Instructions.

### ISSUE THREAD

**Issue by punit9** [CS639A-PAVT/BugTracker#10]
**Feature Request**
Currently the comparison between two Kachua Instructions is not supported. We have to convert them to string and compare, which decreases the readability while using the classes.

**To Reproduce**
Write a simple code:
from kast import kachuaAST as kAST
ins1=kAST.AssignmentCommand(':a','3')
ins2=kAST.AssignmentCommand(':a','3')
print(ins1,ins2)
print("Are Equal:", ins1 == ins2)
print("Are Equal:", str(ins1) == str(ins2))

**Screenshots**
![image](https://user-images.githubusercontent.com/47317021/134784053-5790babc-b287-4af7-b7be-9d63ee74102e.png)

**Additional Info**
The operators == and ! = would be helpful for comparing the objects where the two objects are considered equal if their string equivalant is equal else they are considered not equal.
This would be useful for all the Kachua instructions like Move Commands, Condition Commands etc.

**Comment by lahiri-phdworks** [comment]
Do you want to check `string` equality only? This can work fine in that case. We already have a way to represent a string, you can use that.
If you intend to check for object equality use (I am not sure if it will be useful in the current setting) then use the `==` operator directly. This results will differ since they represent different python objects.

The output you show here is correct and string equality (structural equality) definitely means the instructions are string identical. Best to do this at the point where the comparison is needed.

**Comment by lahiri-phdworks** [comment]
We are closing this issue since it doesn't seem to have a good-use case right now. We can surely take it up later if some involved comparisons are needed.
