### ISSUE TITLE
Passing length of IR to mutate function

### ISSUE THREAD

**Issue by Harsh30199** [CS639A-PAVT/BugTracker#11]
As Sir suggested in today's discussion that we can implement different mutation methods for different level of total coverage but to do this we need length of IR being fuzzed.

So I request that you pass length of IR as an argument to the mutate function being called from fuzzer.py

**Comment by lahiri-phdworks** [comment]
Yes. We have added it now. We pass the whole IR list. You can use it any way you want (except modifying it)
Check v2.3

**Comment by mayanksolanki393** [comment]
@Harsh30199 @lahiri-phdworks This is just for my clarification. Given that Fuzzing is a gray-box method. I don't think we should have access to the source code or even the length of the IR for that matter.

**Comment by lahiri-phdworks** [comment]
It is just for a heuristic. The way we implemented the fuzzer here, it is white-box (even gray-box) since we have the source code and the use that to get the IR. We anyways have the whole IR available for the interpreter. 
A true black-box approach must not have access to the source code and only the binary of the program (for use in Kachua, IR List is the binary equivalent so far), so exposing properties of this binary (length of the IR List) is fine.
