### ISSUE TITLE
Abstract Interpretation: Possible Bug 

### ISSUE THREAD

**Issue by mayank393** [CS639A-PAVT/BugTracker#20]
I am actually seeing an error. For which I am not able to determine the source.
```
File "<snip>/KachuaCore/abstractInterpretation.py", line 107, in worklistAlgorithm
    inlist.append(bbOut[pred.name][0])
IndexError: list index out of range
```

In abstractinterpretation.py at line 94, I can see
```
bbOut[i.name] = []
```
which seems to be initializing the bbOut as empty. At 107 the code is referring to an element in bbOut like 
```
bbOut[pred.name][0]
```
since bbOut is empty the error is expected. Between lines 94 and 107, bbOut is not reassigned or passed to any other function.

Can you confirm if this is as per design and after correctly implementing the "submissionAI.py" this error would not occur?

**Comment by pkalita595** [comment]
Algorithm  assign values to bbOut using return value of transfer function. This bug should not arise if you complete submissionAI.py--PankajOn 09-Nov-2021 11:48 PM, Mayank Solanki ***@***.***> wrote:
I am actually seeing an error. For which I am not able to determine the source.
File "<snip>/KachuaCore/abstractInterpretation.py", line 107, in worklistAlgorithm
    inlist.append(bbOut[pred.name][0])
IndexError: list index out of range

In abstractinterpretation.py at line 94, I can see
bbOut[i.name] = []

which seems to be initializing the bbOut as empty. At 107 the code is referring to an element in bbOut like
bbOut[pred.name][0]

since bbOut is empty the error is expected. Between lines 94 and 107, bbOut is not reassigned or passed to any other function.
Can you confirm if this is as per design and after correctly implementing the "submissionAI.py" this error would not occur?

**Comment by mayank393** [comment]
Got it, Thanks for the confirmation.
